### ISSUE TITLE
`addMinter` function sets the sender as minter, not the target account

### ISSUE THREAD

**Issue by merc1er** [ApeAcademy/ERC20#14]
In `addMinter` [line 156](https://github.com/ApeAcademy/ERC20/blob/3b1cac5fbbcda904e08a7e47b980f281c830b828/%7B%7Bcookiecutter.project_name%7D%7D/contracts/Token.vy#L156), I think there is an error as to which account becomes a minter.

Shouldn't `minter` become minter? i.e.:

```python
@external
def addMinter(minter: address) -> bool:
    assert msg.sender == self.owner
    self.isMinter[minter] = True   # This line changes
    return True  # Also we probably want to add a return value to make this gas efficient
```

**Comment by fubuloubu** [comment]
Oh yes, good find! Will accept a PR if you have the time for it, perhaps with an update to the test so that this issue shows up

**Comment by merc1er** [comment]
I'll work on a PR.
