### ISSUE TITLE
Transferring tokens to a zero address is allowed, but does not decrease total supply

### ISSUE THREAD

**Issue by merc1er** [ApeAcademy/ERC20#17]
Sending tokens to a zero address (i.e. burning them, as per burn function) should decrease total supply. I suggest that instead, sending to a zero address be forbidden. Same goes for minting to a zero address.

**Comment by fubuloubu** [comment]
This is always a tough philosophical point. On the one hand, you can easily prevent users from loosing their own money by blocking the zero address as a target (and also the contract's address is a typical one)

On the other hand, it costs extra gas to do this, and it's better left up to a front end to block these types of addresses (and others) since that's a free check you can do client-side

**Comment by merc1er** [comment]
I think it's not so much about preventing users to lose their money, but more about the total supply variable to be incorrect.

We define `burn` to send to zero address.

So say there is a total supply of 1,000. User A uses the burn function and burns 100 tokens.
Total supply is now 900. Then user B transfers 100 tokens to the zero address by using the `transfer` function instead; the total supply becomes incorrect as it remains 900 instead of 800.

So I think there is a logic problem here. There are multiple ways of solving this. I personally think preventing `transfer` to target zero address is cleaner. But it could be that we handle total supply in `transfer` too via an `if` statement, or other.

**Comment by fubuloubu** [comment]
> I think it's not so much about preventing users to lose their money, but more about the total supply variable to be incorrect.
> 
> We define `burn` to send to zero address.
> 
> So say there is a total supply of 1,000. User A uses the burn function and burns 100 tokens. Total supply is now 900. Then user B transfers 100 tokens to the zero address by using the `transfer` function instead; the total supply becomes incorrect as it remains 900 instead of 800.
> 
> So I think there is a logic problem here. There are multiple ways of solving this. I personally think preventing `transfer` to target zero address is cleaner. But it could be that we handle total supply in `transfer` too via an `if` statement, or other.

"burn" and "transfer" to 0x0 are different here though, the ERC specifies that a burn should "simulate a transfer to 0x0" (for the `Transfer` event) but yes if you read it literally it would mean that any transfers to 0x0 should also be "burnt"

We can add this easily enough
